---
- name: Update Ansible Tower Inventory
  hosts: localhost
  connection: local
  gather_facts: false
  
  collections:
    - ansible.controller

  tasks:
    - name: Update inventory source
      ansible.controller.inventory_source_update:
        name: "AWS-Source"
        inventory: "AWS Inventory"
        organization: "Default"
        tower_host: "https://ec2-3-147-47-103.us-east-2.compute.amazonaws.com"
        tower_username: "admin"
        tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
        tower_verify_ssl: false