---
- name: Create Windows Server 2016 EC2 Instance
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: Set region-specific variables
      set_fact:
        vpc_id: "{{ region_vars[aws_region].vpc_id }}"
        subnet_id: "{{ region_vars[aws_region].subnet_id }}"
        security_group: "{{ region_vars[aws_region].security_group }}"
        key_name: "{{ region_vars[aws_region].key_name }}"
        instance_type: "t3.medium"

    - name: Verify region variables are set
      debug:
        msg:
          - "Region: {{ aws_region }}"
          - "VPC ID: {{ vpc_id }}"
          - "Subnet ID: {{ subnet_id }}"
          - "Security Group: {{ security_group }}"
          - "Key Name: {{ key_name }}"
          - "AMI ID: {{ ami_id }}"

  tasks:
    - name: Create Windows EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        region: "{{ aws_region }}"
        image_id: "{{ ami_id }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        security_group: "{{ security_group }}"
        network:
          assign_public_ip: true
          subnet_id: "{{ subnet_id }}"
        wait: yes
        state: present
        tags:
          Name: "{{ instance_name }}"
          OS: "Windows"
      register: ec2
    
    - name: Wait 2 minutes 
      pause:
        seconds: 120
    
    - name: Associate IAM role with instance
      amazon.aws.ec2_instance:
        instance_ids: "{{ ec2.instance_ids }}"
        region: "{{ aws_region }}"
        iam_instance_profile: "{{ ssm_role_name }}"
        state: present
      register: ec2_with_role
    
    - name: Execute WinRM and CredSSP configuration via SSM
      amazon.aws.ssm_send_command:
        instance_ids: "{{ ec2.instance_ids }}"
        document_name: "AWS-RunPowerShellScript"
        comment: "Configure WinRM and CredSSP"
        parameters:
          commands:
            - winrm quickconfig
            - Enable-WSManCredSSP -Role Client -DelegateComputer "*.domain.com"
            - Enable-WSManCredSSP -Role Server
            - New-NetFirewallRule -DisplayName "WinRM HTTPS" -Direction Inbound -LocalPort 5986 -Protocol TCP -Action Allow
            - |
              $Hostname = $env:COMPUTERNAME
              $Cert = New-SelfSignedCertificate -DnsName $Hostname -CertStoreLocation "Cert:\LocalMachine\My"
              $Thumbprint = $Cert.Thumbprint
            - winrm create winrm/config/Listener?Address=*+Transport=HTTPS "@{Hostname=`"$Hostname`";CertificateThumbprint=`"$Thumbprint`"}"
            - winrm enumerate winrm/config/listener
            - Set-Item -Path WSMan:\*********\Service\Auth\CredSSP -Value $true
            - Set-Item -Path WSMan:\*********\Service\AllowUnencrypted -Value $false
