---
- name: Create Windows Server 2016 EC2 Instance
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: Set region-specific variables
      set_fact:
        vpc_id: "{{ region_vars[aws_region].vpc_id }}"
        subnet_id: "{{ region_vars[aws_region].subnet_id }}"
        security_group: "{{ region_vars[aws_region].security_group }}"
        key_name: "{{ region_vars[aws_region].key_name }}"
        instance_type: "t3.medium"
        instance_name: "Windows-Server-2016-{{ aws_region }}"

    - name: Verify region variables are set
      debug:
        msg:
          - "Region: {{ aws_region }}"
          - "VPC ID: {{ vpc_id }}"
          - "Subnet ID: {{ subnet_id }}"
          - "Security Group: {{ security_group }}"
          - "Key Name: {{ key_name }}"
          - "AMI ID: {{ ami_id }}"

  tasks:
    - name: Create Windows EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        region: "{{ aws_region }}"
        image_id: "{{ ami_id }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        security_group: "{{ security_group }}"
        network:
          assign_public_ip: true
          subnet_id: "{{ subnet_id }}"
        wait: yes
        state: present
        tags:
          Name: "{{ instance_name }}"
          OS: "Windows"
          Environment: "Development"
        user_data: |
          <powershell>
          # Enable & Configure WinRM
            winrm quickconfig
          # Configurate and enable CredSSP
            Enable-WSManCredSSP -Role Client -DelegateComputer "*.domain.com"
            Enable-WSManCredSSP -Role Server
          # Create Firewall rule to allow por 5986
             New-NetFirewallRule -DisplayName "WinRM HTTPS" -Direction Inbound -LocalPort 5986 -Protocol TCP -Action Allow
          # Create SSP Certificate
            $Hostname = $env:COMPUTERNAME
            $Cert = New-SelfSignedCertificate -DnsName $Hostname -CertStoreLocation "Cert:\LocalMachine\My"
            $Thumbprint = $Cert.Thumbprint
          # Configure WinRM Listeners
            winrm create winrm/config/Listener?Address=*+Transport=HTTPS "@{Hostname=`"$Hostname`";CertificateThumbprint=`"$Thumbprint`"}"
            winrm enumerate winrm/config/listener
            Set-Item -Path WSMan:\localhost\Service\Auth\CredSSP -Value $true
            Set-Item -Path WSMan:\localhost\Service\AllowUnencrypted -Value $false
          </powershell>
      register: ec2

    - name: Wait for WinRM to become available
      wait_for:
        host: "{{ ec2.instances[0].private_ip_address }}"
        port: 5986
        timeout: 600
      when: ec2.instances is defined

    - name: Add instance to in-memory inventory
      add_host:
        name: "{{ ec2.instances[0].private_ip_address }}"
        groups: windows_servers
        ansible_host: "{{ ec2.instances[0].private_ip_address }}"
        ansible_connection: winrm
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 5986
        ansible_winrm_scheme: https
      when: ec2.instances is defined

    - name: Output instance information
      debug:
        msg: 
          - "Instance ID: {{ ec2.instances[0].instance_id }}"
          - "Private IP: {{ ec2.instances[0].private_ip_address }}"
          - "Public IP: {{ ec2.instances[0].public_ip_address }}"
      when: ec2.instances is defined

- name: Configure Windows Instance
  hosts: windows_servers
  gather_facts: false
  vars:
    ansible_user: ansible-dev
    ansible_password: "{{ windows_password }}"

  tasks:
    - name: Wait for system to become reachable
      win_ping:
      register: ping_result
      until: ping_result is success
      retries: 30
      delay: 10

    - name: Ensure WinRM is properly configured
      win_shell: |
        Enable-WSManCredSSP -Role Server -Force
        Set-Item -Path WSMan:\localhost\Service\Auth\CredSSP -Value $true
        Restart-Service WinRM
      ignore_errors: yes