---
- name: Check webserver
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - http://ec2-18-223-211-145.us-east-2.compute.amazonaws.com/
        delay: 60
  rules:
    - name: Check webserver
      condition: event.url_check.status == "up"
      action:
        run_job_template:
          name: "web checks are good"
          organization: Default
