windows_patching_reboot_server: false
windows_patching_categories:
  - Application
  - Connectors
  - CrticalUpdates
  - DefinitionUpdates
  - DeveloperKits
  - FeaturePacks Guidance
  - SecurityUpdates
  - ServicePacks
  - Tools
  - UpdateRollups
  - Updates