---
- name: Create a clientssl profile
  hosts: f5demo
  gather_facts: false

  collections:
    - f5networks.f5_modules
    
  tasks:
    - name: Setting up provider values
      set_fact:
       provider:
        server: "{{ inventory_hostname }}"
        server_port: "8443" # on-prem "443" public cloud "8443"
        validate_certs: "False"
 
    - name: Create a client SSL profile with a cert/key/chain setting
      delegate_to: localhost
      bigip_profile_client_ssl:
        provider: "{{provider}}"
        state: present
        name: "{{profile_name}}"
        ciphers: "!SSLv3:ECDHE+AES-GCM+SHA256:ECDHE-RSA-AES128-CBC-SHA"
        cert_key_chain:
          - cert: cool.crt
            key: cool.key